DROP DATABASEIF EXISTS bamazon;

CREATE DATABASE bamazon;
use bamazon;

CREATE TABLE products (
    ITEM_ID INTERGER(15) NOT NULL AUTO_INCREMENT,
    PRODUCT NAME VARCHAR(60) NOT NULL,
    DEPARTMENT_NAME VARCHAR(50) NOT NULL,
    CUSTOMER_COST FLOAT(8,2) NOT NULL,
    PRIMARY KEY (ITEM ID)
);





INSERT INTO products (PRODUCT_NAME, CUSTOMER_COST, STOCK_QUANTITY)
VALUES ("ICE CREAM", "DAIRY", 9.99, 10),
("WOK", "KITCHENWARE", 19.99, 6),
("ANDROID NOTE 8", "ELECTRONICS", 300.00, 7),
("LAUNDRY DETERGENT", "HOME GOODS", 9.99, 6),
("WATERMELON", "PRODUCE", 5.99, 25),
("EGGS", "PRODUCE", 1.99, 10),
("SALMON", "PRODUCE", 8.99, 7),
("GLOVES", "CLOTHES", 12.99, 15),
("RAMEN", "PRODUCE", 12.99, 30),
("GARBAGE BAGS", "HOME GOODS", 7.99, 10);

